{
    "th06_01": "A Dream More Scarlet than Red",
    "th06_02": "A Soul as Red as a Ground Cherry",
    "th06_03": "Apparitions Stalk the Night",
    "th06_04": "Lunate Elf",
    "th06_05": "Tomboyish Girl in Love",
    "th06_06": "Shanghai Teahouse ~ Chinese Tea",
    "th06_07": "Shanghai Alice of Meiji 17",
    "th06_08": "Voile, the Magic Library",
    "th06_09": "Locked Girl ~ The Girl's Secret Room",
    "th06_10": "The Maid and the Pocket Watch of Blood",
    "th06_11": "Lunar Clock ~ Luna Dial",
    "th06_12": "The Young Descendant of Țepeș",
    "th06_13": "Septette for a Dead Princess",
    "th06_14": "The Centennial Festival for Magical Girls",
    "th06_15": "U.N. Owen was Her?",
    "th06_16": "An Eternity More Transient than Scarlet",
    "th06_17": "Scarlet Tower ~ Eastern Dream...",
    "th07_01": "Mystical Dream ~ Snow or Cherry Petal",
    "th07_02": "Paradise ~ Deep Mountain",
    "th07_03": "Crystallized Silver",
    "th07_04": "The Fantastic Tales from Tōno",
    "th07_05": "Diāo Yè Zōng (withered leaf)",
    "th07_06": "The Doll Maker of București",
    "th07_07": "Doll Judgment ~ The Girl Who Played with People's Shapes",
    "th07_08": "The Capital City of Flowers in the Sky",
    "th07_09": "Ghostly Band ~ Phantom Ensemble",
    "th07_10": "Eastern Mystical Dream ~ Ancient Temple",
    "th07_11": "Hiroari Shoots a Strange Bird ~ Till When?",
    "th07_12": "Ultimate Truth",
    "th07_13": "Bloom Nobly, Ink-Black Cherry Blossom ~ Border of Life",
    "th07_14": "Border of Life",
    "th07_15": "Youkai Domination",
    "th07_16": "A Maiden's Illusionary Funeral ~ Necro-Fantasy",
    "th07_17": "Youkai Domination ~ Who done it!",
    "th07_18": "Necrofantasia",
    "th07_19": "Dream of a Spring Breeze",
    "th07_20": "Sakura, Sakura ~ Japanize Dream...",
    "th08_01": "Eternal Night Vignette ~ Eastern Night",
    "th08_02": "Illusionary Night ~ Ghostly Eyes",
    "th08_03": "Stirring an Autumn Moon ~ Mooned Insect",
    "th08_04": "Song of the Night Sparrow ~ Night Bird",
    "th08_05": "Deaf to All but the Song",
    "th08_06": "Nostalgic Blood of the East ~ Old World",
    "th08_07": "Plain Asia",
    "th08_08": "Retribution for the Eternal Night ~ Imperishable Night",
    "th08_09": "Maiden's Capriccio ~ Dream Battle",
    "th08_10": "Love-Colored Master Spark",
    "th08_11": "Cinderella Cage ~ Kagome-Kagome",
    "th08_12": "Lunatic Eyes ~ Invisible Full Moon",
    "th08_13": "Voyage 1969",
    "th08_14": "Gensokyo Millennium ~ History of the Moon",
    "th08_15": "Flight of the Bamboo Cutter ~ Lunatic Princess",
    "th08_16": "Voyage 1970",
    "th08_17": "Extend Ash ~ Person of Hourai",
    "th08_18": "Reach for the Moon, Immortal Smoke",
    "th08_19": "Evening Primrose",
    "th08_20": "Eternal Dream ~ Mystical Maple",
    "th08_21": "Eastern Youkai Beauty",
    "th09_01": "Flower Viewing Mound ~ Higan Retour",
    "th09_02": "Spring Lane ~ Colorful Path",
    "th09_03": "Oriental Dark Flight",
    "th09_04": "Flowering Night",
    "th09_05": "Eastern Mystical Dream ~ Ancient Temple",
    "th09_06": "Lunatic Eyes ~ Invisible Full Moon",
    "th09_07": "Adventure of the Lovestruck Tomboy",
    "th09_08": "Ghostly Band ~ Phantom Ensemble",
    "th09_09": "Deaf to All but the Song ~ Flower Mix",
    "th09_10": "White Flag of Usa Shrine",
    "th09_11": "Wind God Girl",
    "th09_12": "Poison Body ~ Forsaken Doll",
    "th09_13": "Gensokyo, Past and Present ~ Flower Land",
    "th09_14": "Higan Retour ~ Riverside View",
    "th09_15": "Eastern Judgement in the Sixtieth Year ~ Fate of Sixty Years",
    "th09_16": "The Mound where the Flowers Reflect",
    "th09_17": "Mound of Shigan",
    "th09_18": "The Flowers Remain in Fantasy",
    "th09_19": "Flower of Soul ~ Another Dream...",
    "th095_01": "Tengu's Notebook ~ Mysterious Note",
    "th095_02": "Wind Circulation ~ Wind Tour",
    "th095_03": "Tengu is Watching ~ Black Eyes",
    "th095_04": "Sleepless Night of the Eastern Country",
    "th095_05": "Retrospective Kyoto",
    "th095_06": "Wind God Girl",
    "th10_01": "Sealed Gods",
    "th10_02": "A God That Misses People ~ Romantic Fall",
    "th10_03": "Because Princess Inada Is Scolding Me",
    "th10_04": "The Road of the Misfortune God ~ Dark Road",
    "th10_05": "Dark Side of Fate",
    "th10_06": "The Gensokyo the Gods Loved",
    "th10_07": "Akutagawa Ryuunosuke's \"Kappa\" ~ Candid Friend",
    "th10_08": "Fall of Fall ~ Autumnal Waterfall",
    "th10_09": "Youkai Mountain ~ Mysterious Mountain",
    "th10_10": "The Primal Scene of Japan the Girl Saw",
    "th10_11": "Faith Is for the Transient People",
    "th10_12": "Cemetery of Onbashira ~ Grave of Being",
    "th10_13": "The Venerable Ancient Battlefield ~ Suwa Foughten Field",
    "th10_14": "Tomorrow Will Be Special, Yesterday Was Not",
    "th10_15": "Native Faith",
    "th10_16": "Shrine at the Foot of the Mountain",
    "th10_17": "The Gods Give Us Blessed Rain ~ Sylphid Dream",
    "th10_18": "Player's Score",
    "th11_01": "Awakening of the Earth Spirits",
    "th11_02": "The Dark Blowhole",
    "th11_03": "The Sealed-Away Youkai ~ Lost Place",
    "th11_04": "The Bridge People No Longer Cross",
    "th11_05": "Green-Eyed Jealousy",
    "th11_06": "Walking the Streets of a Former Hell",
    "th11_07": "A Flower-Studded Saké Dish on Mt. Ooe",
    "th11_08": "Heartfelt Fancy",
    "th11_09": "Satori Maiden ~ 3rd eye",
    "th11_10": "Lullaby of Deserted Hell",
    "th11_11": "Corpse Voyage ~ Be of good cheer!",
    "th11_12": "Hellfire Mantle",
    "th11_13": "Solar Sect of Mystic Wisdom ~ Nuclear Fusion",
    "th11_14": "Last Remote",
    "th11_15": "Hartmann's Youkai Girl",
    "th11_16": "The Earth Spirits' Homecoming",
    "th11_17": "Energy Daybreak ~ Future Dream...",
    "th12_01": "A Shadow in the Blue Sky",
    "th12_02": "At the End of Spring",
    "th12_03": "A Tiny, Tiny, Clever Commander",
    "th12_04": "The Sealed Cloud Route",
    "th12_05": "Beware the Umbrella Left There Forever",
    "th12_06": "Sky Ruin",
    "th12_07": "The Traditional Old Man and the Stylish Girl",
    "th12_08": "Interdimensional Voyage of a Ghostly Passenger Ship",
    "th12_09": "Captain Murasa",
    "th12_10": "Rural Makai City Esoteria",
    "th12_11": "The Tiger-Patterned Vaiśravaṇa",
    "th12_12": "Fires of Hokkai",
    "th12_13": "Emotional Skyscraper ~ Cosmic Mind",
    "th12_14": "UFO Romance in the Night Sky",
    "th12_15": "Heian Alien",
    "th12_16": "Youkai Temple",
    "th12_17": "Returning Home from the Sky ~ Sky Dream",
    "th125_01": "Newshound",
    "th125_02": "The Mystery in Your Town",
    "th125_03": "Youkai Modern Colony",
    "th125_04": "Nemesis's Stronghold",
    "th125_05": "Bell of Avīci ~ Infinite Nightmare",
    "th125_06": "Youkai Mountain ~ Mysterious Mountain",
    "th128_01": "An Ice Fairy in Spring",
    "th128_02": "The Refrain of the Lovely Great War",
    "th128_03": "Staking Your Life on a Prank",
    "th128_04": "Year-Round Absorbed Curiosity",
    "th128_05": "A Midnight Fairy Dance",
    "th128_06": "Great Fairy Wars ~ Fairy Wars",
    "th128_07": "Loose Rain",
    "th128_08": "Magus Night",
    "th128_09": "An Ice Fairy in Spring - still -",
    "th128_10": "Player's Score",
    "th13_01": "Spirit of Avarice",
    "th13_02": "Night Sakura of Dead Spirits",
    "th13_03": "Ghost Lead",
    "th13_04": "Welcome to Youkai Temple",
    "th13_05": "Youkai Girl at the Gate",
    "th13_06": "Let's Live in a Lovely Cemetery",
    "th13_07": "Rigid Paradise",
    "th13_08": "Desire Drive",
    "th13_09": "Old Yuanxian",
    "th13_10": "The Hall of Dreams' Great Mausoleum",
    "th13_11": "Omiwa Legend",
    "th13_12": "Starry Sky of Small Desires",
    "th13_13": "Shoutoku Legend ~ True Administrator",
    "th13_14": "Youkai Back Shrine Road",
    "th13_15": "Futatsuiwa from Sado",
    "th13_16": "A New Wind at the Shrine",
    "th13_17": "Desire Dream",
    "th14_01": "Mysterious Purification Rod",
    "th14_02": "Mist Lake",
    "th14_03": "Mermaid from the Uncharted Land",
    "th14_04": "Humans and Youkai Traversing the Canal",
    "th14_05": "Dullahan Under the Willows",
    "th14_06": "Bamboo Forest of the Full Moon",
    "th14_07": "Lonesome Werewolf",
    "th14_08": "Magical Storm",
    "th14_09": "Illusionary Joururi",
    "th14_10": "The Shining Needle Castle Sinking in the Air",
    "th14_11": "Reverse Ideology",
    "th14_12": "The Exaggerated Castle Keep",
    "th14_13": "Inchlings of the Shining Needle ~ Little Princess",
    "th14_14": "Thunderclouds of Magical Power",
    "th14_15": "Primordial Beat ~ Pristine Beat",
    "th14_16": "Magical Power of the Mallet",
    "th14_17": "Mysterious, Mysterious Tools",
    "th143_01": "Raise the Signal Fire of Cheating",
    "th143_02": "Cheat Against the Impossible Danmaku",
    "th143_03": "Midnight Spell Card",
    "th143_04": "Romantic Escape Flight",
    "th143_05": "Eternal Transient Reign",
    "th143_06": "Mermaid from the Uncharted Land",
    "th143_07": "Reverse Ideology",
    "th143_08": "Illusionary Joururi",
    "th143_09": "Youkai Mountain ~ Mysterious Mountain",
    "th15_01": "The Space Shrine Maiden Appears",
    "th15_02": "Unforgettable, the Nostalgic Greenery",
    "th15_03": "The Rabbit Has Landed",
    "th15_04": "The Lake Reflects the Cleansed Moonlight",
    "th15_05": "September Pumpkin",
    "th15_06": "The Mysterious Shrine Maiden Flying Through Space",
    "th15_07": "Eternal Spring Dream",
    "th15_08": "The Frozen Eternal Capital",
    "th15_09": "The Reversed Wheel of Fortune",
    "th15_10": "Faraway Voyage of 380,000 Kilometers",
    "th15_11": "The Pierrot of the Star-Spangled Banner",
    "th15_12": "The Sea Where the Home Planet is Reflected",
    "th15_13": "Pure Furies ~ Whereabouts of the Heart",
    "th15_14": "A World of Nightmares Never Seen Before",
    "th15_15": "Pandemonic Planet",
    "th15_16": "The Moon as Seen from the Shrine",
    "th15_17": "The Space Shrine Maiden Returns Home",
    "th16_01": "The Sky Where Cherry Blossoms Flutter Down",
    "th16_02": "A Star of Hope Rises in the Blue Sky",
    "th16_03": "A Midsummer Fairy's Dream",
    "th16_04": "The Colorless Wind on Youkai Mountain",
    "th16_05": "Deep-Mountain Encounter",
    "th16_06": "Swim in a Cherry Blossom-Colored Sea",
    "th16_07": "A Pair of Divine Beasts",
    "th16_08": "Illusionary White Traveler",
    "th16_09": "The Magic Straw-Hat Jizo",
    "th16_10": "Does the Forbidden Door Lead to This World, or the World Beyond?",
    "th16_11": "Crazy Backup Dancers",
    "th16_12": "Into Backdoor",
    "th16_13": "The Concealed Four Seasons",
    "th16_14": "No More Going Through Doors",
    "th16_15": "Secret God Matara ~ Hidden Star in All Seasons.",
    "th16_16": "Unnatural Nature",
    "th16_17": "White Traveler",
    "th135_02": "Spring Lane ~ Colorful Path",
    "th135_03": "Magus Night",
    "th135_04": "The Traditional Old Man and the Stylish Girl",
    "th135_05": "Emotional Skyscraper ~ Cosmic Mind",
    "th135_06": "Omiwa Legend",
    "th135_07": "Shoutoku Legend ~ True Administrator",
    "th135_08": "Akutagawa Ryuunosuke's \"Kappa\" ~ Candid Friend",
    "th135_09": "Hartmann's Youkai Girl",
    "th135_10": "Futatsuiwa from Sado",
    "th135_11": "Futatsuiwa from Gensokyo",
    "th135_12": "The Lost Emotion",
    "th135_13": "This Dull World's Unchanging Pessimism",
    "th135_14": "Shinkirou Orchestra",
    "th135_15": "Morning Clouds",
    "th135_16": "Officially-Sanctioned Twilight Newspaper",
    "th135_17": "Today's Front-Page Headline",
    "th135_19": "A Popular Location",
    "th135_20": "An Unpopular Location",
    "th135_22": "The Village in the Dead of Night",
    "th135_23": "Performer Selection",
    "th135_34": "Last Word Unleashed",
    "th105_01": "Heaven of Scarlet Perception",
    "th105_02": "Usual Days",
    "th105_03": "The Ground's Color is Yellow",
    "th105_04": "Argue for and Against",
    "th105_05": "Beautiful Nature Sight",
    "th105_06": "Fragrant Plants",
    "th105_07": "Dancing Water Spray",
    "th105_08": "Swing a Fish to Drive Away Flies",
    "th105_09": "Free and Easy",
    "th105_10": "Ridiculous Game",
    "th105_11": "Drunk as I Like",
    "th105_12": "Skies Beyond the Clouds",
    "th105_13": "Crimson in the Black Sea ~ Legendary Fish",
    "th105_14": "Flawless as Clothing of the Celestials",
    "th105_15": "Catastrophe in Bhavaagra ~ Wonderful Heaven",
    "th105_16": "Bhavaagra As Seen Through a Child's Mind",
    "th105_17": "Darkening Dusk",
    "th105_18": "Eastern Heaven of Scarlet Perception",
    "th105_19": "Eastern Mystical Love Consultation",
    "th105_20": "Vessel of Stars ~ Casket of Star",
    "th105_21": "Flowering Night",
    "th105_22": "The Doll Maker of București",
    "th105_23": "Hiroari Shoots a Strange Bird ~ Till When?",
    "th105_24": "Locked Girl ~ The Girl's Secret Room",
    "th105_25": "Bloom Nobly, Ink-Black Cherry Blossom ~ Border of Life",
    "th105_26": "Septette for a Dead Princess",
    "th105_27": "Night Falls ~ Evening Star",
    "th105_28": "Broken Moon",
    "th105_29": "Lunatic Eyes ~ Invisible Full Moon",
    "th105_30": "Wind God Girl",
    "th105_31": "Higan Retour ~ Riverside View",
    "th123_01": "Did You See that Shadow?",
    "th123_02": "Memory of Forgathering Dream",
    "th123_03": "The Legendary Titan",
    "th123_04": "Faith Is for the Transient People",
    "th123_05": "Tomboyish Girl in Love",
    "th123_06": "The Scenery of Living Dolls",
    "th123_07": "Shanghai Teahouse ~ Chinese Tea",
    "th123_08": "Solar Sect of Mystic Wisdom ~ Nuclear Fusion",
    "th123_09": "Our Hisoutensoku",
    "th123_10": "Unknown X ~ Unfound Adventure",
    "th123_11": "X, the Floating Object in the Sky",
    "th123_12": "Dichromatic Lotus Butterfly ~ Ancients",
    "th123_13": "Love-Coloured Magic",
    "th123_14": "the Grimoire of Alice",
    "th123_15": "Voile, the Magic Library",
    "th123_16": "Tomorrow Will Be Special, Yesterday Was Not",
    "th123_17": "The Eternal Steam Engine",
    "th123_18": "A Huge Shadow and a Tiny Conclusion",
    "th123_19": "Eastern Mystical Love Consultation (Century's End Version)",
    "th075_01": "Memory of Forgathering Dream",
    "sh01_18": "Dichromatic Lotus Butterfly ~ Ancients",
    "th02_09": "Love-Coloured Magic",
    "th05_17": "the Grimoire of Alice",
    "th03_03": "Eastern Mystical Love Consultation",
    "th04_11": "Vessel of Stars ~ Casket of Star",
    "th075_17": "Night Falls ~ Evening Star",
    "th075_34": "Broken Moon",
    "th155_01": "Dichromatic Lotus Butterfly ~ Red and White",
    "th155_02": "Love-Colored Master Spark",
    "th155_03": "The Traditional Old Man and the Stylish Girl",
    "th155_05": "Omiwa Legend",
    "th155_07": "Ryūnosuke Akutagawa's \"Kappa\" ~ Candid Friend",
    "th155_09": "Futatsuiwa from Gensokyo",
    "th155_08": "Hartmann's Youkai Girl",
    "th155_06": "Shoutoku Legend ~ True Administrator",
    "th155_04": "Emotional Skyscraper ~ Cosmic Mind",
    "th155_11": "Reach for the Moon, Immortal Smoke",
    "th155_13": "Battlefield of the Flower Threshold",
    "th155_12": "Inchlings of the Shining Needle ~ Little Princess",
    "th155_16": "Eternal Spring Dream",
    "th155_18": "Night Falls ~ Evening Star",
    "th155_19": "The Ground's Color is Yellow ~ Primrose",
    "th155_15": "Lunatic Eyes ~ Invisible Full Moon",
    "th155_14": "Last Occultism ~ Esotericist of the Present World",
    "th155_10": "The Lost Emotion",
    "th155_17": "Catastrophe in Bhavaagra ~ Wonderful Heaven",
    "th155_41": "Unknown X ~ Occultly Madness",
    "th155_38": "Occult Attract",
    "th155_40": "Bell of Aeons",
    "th155_39": "Neo Bamboo Forest in Flames",
    "th155_22": "Equality Under the Law of Dharma",
    "th155_21": "The Palanquin Ship Flies in the Sky",
    "th155_20": "Mushroom Waltz",
    "th155_24": "Shining Armillary Sphere",
    "th155_25": "The Ravine Kappa's Technological Prowess",
    "th155_26": "A Rose Blooming in the Underworld",
    "th155_37": "Tonight Stars an Easygoing Egoist (Live ver.) ~ Egoistic Flowers.",
    "th155_36": "Yorimashi Between Dreams and Reality ~ Necro-Fantasia",
    "th155_35": "Bhavaagra as Far as the Eye Can See",
    "th155_34": "Sleep Sheep Parade",
    "th155_33": "Corridor Stretching to Eternity",
    "th155_32": "Dream World Folklore",
    "th155_31": "Overcome a Thousand Trials",
    "th155_30": "The Inverted Castle Lit by the Setting Sun",
    "th155_29": "Immortal Red Soul",
    "th155_28": "Shinkirou Theatrical",
    "th155_27": "In the Deep-Green Tanuki Forest",
    "th155_23": "Constant and Unchanging Temple of Worship",
    "th155_58": "The Eternal Steam Engine",
    "th155_50": "Flawless as Clothing of the Celestials ~ Yellow Lily",
    "th155_42": "Being Things Eye To Eye",
    "th155_43": "The One Jointly Responsible",
    "th155_44": "An Odd Couple",
    "th155_45": "Two Minds of One Body",
    "th155_46": "Grandiloquence",
    "th155_47": "Scheming Outside the Box",
    "th155_48": "In High Spirits",
    "th155_49": "The Curtain Shall Rise Soon",
    "th155_51": "Seeds of the Incident",
    "th155_52": "Sprouts of Suspicion",
    "th155_53": "Branches Reaching to the Truth",
    "th155_54": "Blizzard of Scattering Possession Flowers",
    "th155_55": "Floating with the Tide",
    "th155_56": "Possession Flowers Yet to Bud",
    "th155_57": "Possession Flowers in Full Bloom",
    "none": "(none)",
    "th_main": "Theme of Eastern Story",
    "th01_12a": "We Shall Die Together",
    "th02_01": "Eastern Demon-Sealing Record ~ Pure Land Mandala",
    "th02_10": "Eastern Demon-Sealing Record ~ A Phantom's Boisterous Dance",
    "th03_14": "Adoration of Magic",
    "th03_21": "Ghostly Person's Holiday",
    "th05_03": "Magic Circle ~ Magic Square",
    "mcd_03_03": "Shanghai Teahouse ~ Chinese Tea",
    "mcd_02_01": "Passing On through the Dendera Fields in the Night",
    "mcd_02_04": "Ancient Temple of the Netherworld",
    "mcd_02_06": "Merry the Magician",
    "mcd_02_11": "Eternal Festival of Illusions",
    "mcd_03_05": "Boys and Girls of the Age of Science",
    "mcd_03_09": "Border Between Dreams and Reality",
    "th125_07": "Hatate Unlock",
    "mcd_07_01": "Green Sanatorium",
    "th165_05": "Old Adam Bar",
    "th165_06": "The Darkness Brought In by Swallowstone Naturalis Historia",
    "th165_07": "Eternal Spring Dream",
    "th165_08": "The Concealed Four Seasons",
    "th165_04": "Nightmare Diary",
    "th165_03": "Lunatic Dreamer",
    "th165_02": "Lucid Dreamer",
    "th165_01": "Diary of Nightmares",
    "mcd_08_11": "Eternal Transient Reign",
    "mcd_03_02": "Dream of Kasho",
    "th03_06": "Tabula rasa ~ The Empty Girl",
    "th03_08": "Vanishing Dream ~ Lost Dream",
    "th03_09": "Visionary Game ~ Dream War",
    "th03_11": "Decisive Magic Battle! ~ Fight it out!",
    "th04_15": "Faint Dream ~ Inanimate Dream",
    "th04_16": "The Inevitably Forbidden Game",
    "th04_17": "Illusion of a Maid ~ Icemilk Magic",
    "th16_18": "Player's Score",
    "th15_18": "Player's Score",
    "th145_28": "The Lost Emotion",
    "th145_27": "Futatsuiwa from Gensokyo"
}